### ISSUE TITLE
Move all TODO pages to correct sections

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/docs#22]
- [ ] MessageBus/getting_started
- [ ] MessageBus/message_recorder
- [ ] MessageBus/upgrade_guide
- [ ] SymfonyBridge/getting_started
- [ ] SymfonyBridge/upgrade_guide
